FROM microsoft/dotnet:latest

ENV ASPNETCORE_ENVIRONMENT docker

COPY SimpleIdentityServer/src /app

WORKDIR /app

RUN dotnet restore
RUN apt-get update && apt-get install postgresql-client
# RUN bash -c "./wait-for-it.sh postgresql:5432 -- cd SimpleIdentityServer.DataAccess.SqlServer && dotnet ef database update"

EXPOSE 5000

ENTRYPOINT ["dotnet", "run", "--project", "SimpleIdentityServer.Startup/project.json"]