FROM microsoft/dotnet:latest

ENV ASPNETCORE_ENVIRONMENT docker
ENV DB_ALIAS postgresql
ENV DB_PORT 5432

COPY SimpleIdentityServer/src /app

WORKDIR /app

RUN dotnet restore

EXPOSE 5000

ENTRYPOINT ["/simpleidserver-entrypoint.sh"]