SET IS_TOOLS_DISABLED=true
SET IS_RESOURCES_DISABLED=true
SET IS_CONNECTIONS_DISABLED=true
SET IS_SETTINGS_DISABLED=true
SET IS_CACHE_DISABLED=true
SET IS_MANAGE_DISABLED=true
SET BASE_URL="http://localhost:60004"
SET EVT_SOURCE_URL="http://localhost:60002"
webpack