import About from './about';
import Login from './login';
import Logs from './logs';
import Resources from './resources';
import ViewAggregate from './viewAggregate';
import ViewLog from './viewLog';
import OAuthClients from './oauthClients';
import OpenidClients from './openidClients';
import OAuthScopes from './oauthScopes';
import OpenidScopes from './openidScopes';
import ResourceOwners from './resourceOwners';
import ViewResource from './viewResource';
import ViewClient from './viewClient';
import ViewScope  from './viewScope';

exports.About = About;
exports.Login = Login;
exports.Logs = Logs;
exports.Resources = Resources;
exports.ViewLog = ViewLog;
exports.ViewAggregate = ViewAggregate;
exports.OAuthClients = OAuthClients;
exports.OpenidClients = OpenidClients;
exports.OAuthScopes = OAuthScopes;
exports.OpenidScopes = OpenidScopes;
exports.ResourceOwners = ResourceOwners;
exports.ViewResource = ViewResource;
exports.ViewClient = ViewClient;
exports.ViewScope = ViewScope;