import About from './about';
import Login from './login';
import Logs from './logs';
import Cache from './cache';
import Manage from './manage';
import Tools from './tools';
import Resources from './resources';
import ViewAggregate from './viewAggregate';
import ViewLog from './viewLog';
import OAuthClients from './oauthClients';

exports.About = About;
exports.Login = Login;
exports.Logs = Logs;
exports.Cache = Cache;
exports.Manage = Manage;
exports.Tools = Tools;
exports.Resources = Resources;
exports.ViewLog = ViewLog;
exports.ViewAggregate = ViewAggregate;
exports.OAuthClients = OAuthClients;